services:
  - type: web
    name: fri-api
    env: node
    rootDir: api-service
    region: frankfurt
    plan: starter
    previewPlan: starter    
    buildCommand: npm ci
    startCommand: node ./server/index.js
    pullRequestPreviewsEnabled: true
    domains:
      - api.fri.is
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fri-api-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: fri-api-store
          property: connectionString
      - fromGroup: Thor
      - fromGroup: Mailgun    
  - type: web
    name: fri-admin
    env: static
    rootDir: admin
    buildCommand: npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    domains:
      - admin.fri.is
    envVars:
      - key: API_FRIDOMAIN_URL
        value: https://api.fri.is
      - key: API_ONRENDER_URL
        fromService:
          type: web
          name: fri-api
          envVarKey: RENDER_EXTERNAL_URL          
  - type: redis
    name: fri-api-store
    region: frankfurt
    plan: starter    
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
databases:
  - name: fri-api-db
    plan: starter
    previewPlan: starter
    region: frankfurt
