previewsEnabled: true
previewsExpireAfterDays: 3
services:
  - type: web
    name: fri-api-test
    repo: https://github.com/frjalsar/monorepo.git
    env: node    
    rootDir: api-service
    region: frankfurt
    plan: starter
    previewPlan: starter
    initialDeployHook: ../preview-domains.sh
    buildCommand: npm ci
    startCommand: node ./server/index.js
    autoDeploy: true
    domains:
      - api-test.fri.is
    envVars:
      - key: FRI_HOST
        value: api-test.fri.is
      - key: DATABASE_URL
        fromDatabase:
          name: fri-db-test
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: fri-store-test
          property: connectionString
      - fromGroup: Thor
      - fromGroup: Mailgun
      - fromGroup: renderApi
  - type: web    
    name: fri-admin-test
    repo: https://github.com/frjalsar/monorepo.git
    env: static        
    rootDir: admin
    initialDeployHook: ../preview-domains.sh
    buildCommand: vite-url.sh; npm run build
    staticPublishPath: ./dist
    autoDeploy: true
    domains:
      - admin-test.fri.is
    envVars:
      - key: FRI_HOST
        value: admin-test.fri.is
      - key: FRI_API_HOST
        value: api-test.fri.is      
      - fromGroup: renderApi
  - type: redis
    name: fri-store-test
    region: frankfurt
    plan: starter    
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
databases:
  - name: fri-db-test
    plan: starter
    previewPlan: starter
    region: frankfurt
