previewsEnabled: true
previewsExpireAfterDays: 3
services:
  - type: web
    plan: starter
    previewPlan: starter
    name: api-service
    env: node
    buildCommand: npm ci
    startCommand: node ./server/index.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
databases:
  - name: postgres
    plan: starter
    previewPlan: starter
