previewsEnabled: true
previewsExpireAfterDays: 3
services:
  - type: web
    plan: starter
    previewPlan: starter
    region: frankfurt
    name: fri-api
    env: node
    buildCommand: npm ci
    startCommand: node ./server/index.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: api-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: api-store
          property: connectionString
      - fromGroup: Thor
      - fromGroup: Mailgun
  - type: redis
    name: api-store
    plan: starter
    region: frankfurt
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
databases:
  - name: api-db
    plan: starter
    previewPlan: starter
    region: frankfurt
