previewsEnabled: true
previewsExpireAfterDays: 3
services:
  - type: web
    plan: starter
    previewPlan: starter
    name: api-service
    env: node
    buildCommand: npm ci
    startCommand: node ./server/index.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: api-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: api-store
          property: connectionString
  - type: redis
    name: api-store
    plan: starter
databases:
  - name: api-db
    plan: starter
    previewPlan: starter
