previewsEnabled: true
previewsExpireAfterDays: 3
services:
  - type: web
    name: fri-api
    env: node
    rootDir: api
    region: frankfurt
    plan: starter
    previewPlan: starter    
    buildCommand: npm ci
    startCommand: node ./server/index.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fri-api-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: fri-api-store
          property: connectionString
      - fromGroup: Thor
      - fromGroup: Mailgun    
  - type: web
    name: fri-admin
    env: static
    rootDir: admin
    buildCommand: npm ci; npm run build
    staticPublishPath: ./dist
  - type: redis
    name: fri-api-store
    region: frankfurt
    plan: starter    
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
databases:
  - name: fri-api-db
    plan: starter
    previewPlan: starter
    region: frankfurt
