previewsEnabled: true
previewsExpireAfterDays: 30
services:  
  - type: web    
    name: fri-admin-test
    repo: https://github.com/frjalsar/monorepo.git
    env: static        
    rootDir: admin
    buildCommand: ./vite-url.sh; npm run build-test
    staticPublishPath: ./dist
    autoDeploy: true
    domains:
      - admin-test.fri.is
    envVars:
      - key: VITE_FRI_API_URL
        value: https://api-test.fri.is      
      - key: VITE_COUNTRIES_API_URL
        value: https://restcountries.com     
      - fromGroup: RenderApi
  - type: web
    name: fri-api-test
    repo: https://github.com/frjalsar/monorepo.git
    env: node    
    rootDir: api-service
    region: frankfurt
    plan: starter
    previewPlan: starter
    initialDeployHook: ./preview-domains.sh; node ./migrations.js
    buildCommand: npm ci
    startCommand: node ./server/index.js
    autoDeploy: true
    domains:
      - api-test.fri.is
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fri-db-test
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: fri-store-test
          property: connectionString
      - fromGroup: Thor
      - fromGroup: Mailgun
      - fromGroup: RenderApi
  - type: redis
    name: fri-store-test
    region: frankfurt
    plan: starter    
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
databases:
  - name: fri-db-test
    plan: starter
    previewPlan: starter
    region: frankfurt
